export enum companyActionType {
  GET_COMPANY_STARTED = "GET_COMPANY_STARTED",
  GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS",
  GET_COMPANY_ERROR = "GET_COMPANY_ERROR",
  UPDATE_COMPANY_STARTED = "UPDATE_COMPANY_STARTED",
  UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS",
  UPDATE_COMPANY_ERROR = "UPDATE_COMPANY_ERROR",
  CLEAR_COMPANY = "CLEAR_COMPANY",
}
