# Extending image
FROM mhart/alpine-node:10

# app directory
WORKDIR '/app'

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Environment variables
ENV NODE_ENV test

# Main command
CMD [ "npm", "run", "test:coverage" ]