version: "3"
services:
  spa-service:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    command: npm run start
