FROM node:12-alpine

WORKDIR '/app'

COPY package.json .
COPY package-lock.json .

RUN set -eux \
  & apk add \
  --no-cache \
  nodejs \
  yarn

RUN yarn install

COPY . .

# CMD ["npm", "run", "start"]