export enum deviceActionType {
  GET_DEVICE_HISTORY_STARTED = 'GET_DEVICE_HISTORY_STARTED',
  GET_DEVICE_HISTORY_SUCCESS = 'GET_DEVICE_HISTORY_SUCCESS',
  GET_DEVICE_HISTORY_ERROR = 'GET_DEVICE_HISTORY_ERROR',
}
